# 도커 컴포즈 명령어
# docker compose up -d : 실행
# docker compose down : 제거
version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=batch
      - MYSQL_USER=batch
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci