spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
      enabled: true